body = '''
default
body
'''

[headers]
accept-encoding = 'gzip, deflate, br'
sec-fetch-dest = 'image'
Krzysztof = 'Kuś'

[[paths]]
path = 'path1'
method = 'GET'
body = 'body1'
[paths.headers]
a = '1'
b = '2'

[[paths]]
path = 'path2'
method = 'GET'
body = 'body2'
[paths.headers]
a = '3'
b = '4'